# Generated by Django 4.1.5 on 2023-01-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test01", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test01",
            options={"managed": True},
        ),
    ]
