# Generated by Django 4.1.5 on 2023-02-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test01", "0002_alter_test01_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("files", models.FileField(null=True, upload_to="documents")),
                ("upload_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="test01",
            name="keyword",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
