# Generated by Django 4.1.5 on 2023-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test01", "0002_alter_test01_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="test01",
            name="keyword",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
